### ISSUE TITLE
NPC processing error(?)

### ISSUE THREAD

**Issue by MandL27** [pmdcp/Client#3]
"- First NPC in the Map Editor NPC list is the only NPC that is visible on the map.
- NPCs appear for a brief moment when the map is saved.
- NPCs will appear and stay if a map is reloaded. (Until the player leaves the map.)
- Player 1 and Player 2 are on the same map. This map is reloaded. Player 1 leaves the map and comes back. Player 1’s NPCs are broken while Player 2’s NPCs are working correctly.
- Broken NPCs do not appear on the minimap and sometimes are shown in the wrong locations.
- You can walk through invisible NPCs.
- You can interact with invisible NPCs." ~ Erica/rentheluxray on Skype

**Comment by pzaps** [comment]
Should be fixed in c9c31c1c7e
